import { BlueprintData } from './types';

export const initialData: BlueprintData = {
  projectName: 'CUSTOMER\nAFFILIATION',
  projectSubtitle: 'PG',
  scenario: 'TBD',
  personas: [
    { id: 'p1', name: 'Persona', jobs: ['TBD', 'TBD'] },
    { id: 'p2', name: 'Persona', jobs: ['TBD', 'TBD', 'TBD'] },
    { id: 'p3', name: 'Persona', jobs: ['TBD', 'TBD', 'TBD'] },
    { id: 'p4', name: 'Persona', jobs: ['TBD', 'TBD'] },
  ],
  phases: [
    { id: 'ph1', name: 'PREPARE', duration: '1 Week' },
    { id: 'ph2', name: 'ENGAGE', duration: '1 Week' },
    { id: 'ph3', name: 'PROVIDE', duration: '3 Weeks' },
    { id: 'ph4', name: 'LOG', duration: '1 Week' },
  ],
  sections: [
    {
      id: 's1', type: 'service-journey',
      label: 'SERVICE\nJOURNEY',
      bg: '#F8F8F8', accent: '#D4D4D4',
      laneIds: ['l1'],
    },
    {
      id: 's2', type: 'customer',
      label: 'CUSTOMER\nJOURNEY',
      sectionHeader: 'WHAT THE CUSTOMER SEES',
      bg: '#EDF7ED', accent: '#A8D5A8',
      laneIds: ['l2', 'l3'],
    },
    {
      id: 's3', type: 'frontstage',
      label: 'FRONTSTAGE\nACTION',
      bg: '#FFF4EC', accent: '#FFB870',
      laneIds: ['l4', 'l5'],
    },
    {
      id: 's4', type: 'backstage',
      label: 'BACKSTAGE\nACTION',
      sectionHeader: 'BEHIND THE SCENES',
      bg: '#EAF3FB', accent: '#90BEE0',
      laneIds: ['l6', 'l7', 'l8', 'l9'],
    },
    {
      id: 's5', type: 'tech-stack',
      label: 'TECH\nSTACK',
      bg: '#F5EEF8', accent: '#C490D8',
      laneIds: ['l10', 'l11'],
    },
  ],
  lanes: [
    { id: 'l1', sectionId: 's1', name: 'STORYBOARD' },
    { id: 'l2', sectionId: 's2', name: 'HCP' },
    { id: 'l3', sectionId: 's2', name: 'HCO' },
    { id: 'l4', sectionId: 's3', name: 'Digital Services (Marketing, RTE)' },
    { id: 'l5', sectionId: 's3', name: 'Sales Rep' },
    { id: 'l6', sectionId: 's4', name: 'ABL' },
    { id: 'l7', sectionId: 's4', name: 'ERC Compliance' },
    { id: 'l8', sectionId: 's4', name: 'Sample Ops' },
    { id: 'l9', sectionId: 's4', name: 'DHL' },
    { id: 'l10', sectionId: 's5', name: 'CRM' },
    { id: 'l11', sectionId: 's5', name: 'Training' },
  ],
  tasks: [
    { id: 't1', laneId: 'l1', phaseId: 'ph1', content: 'REVIEWING SAMPLE CART', tags: [] },
    { id: 't2', laneId: 'l1', phaseId: 'ph2', content: 'DECIDING HAND CARRY VS. DTP', tags: [] },
    { id: 't3', laneId: 'l1', phaseId: 'ph3', content: 'IN CONVERSATION WITH HCP', tags: [] },
    { id: 't4', laneId: 'l1', phaseId: 'ph3', content: 'PROVIDING SAMPLE', tags: [] },
    { id: 't5', laneId: 'l1', phaseId: 'ph3', content: 'GETTING SIGNATURE', tags: [] },
    { id: 't6', laneId: 'l1', phaseId: 'ph4', content: 'LOGGING TRANSACTION', tags: [] },
    { id: 't7', laneId: 'l2', phaseId: 'ph1', content: 'Review options', tags: [] },
    { id: 't8', laneId: 'l2', phaseId: 'ph2', content: 'Evaluate proposal', tags: [] },
    { id: 't9', laneId: 'l2', phaseId: 'ph3', content: 'Receive sample', tags: [] },
    { id: 't10', laneId: 'l2', phaseId: 'ph4', content: 'Provide feedback', tags: [] },
    { id: 't11', laneId: 'l5', phaseId: 'ph1', content: 'Pain Point', tags: ['pain-point'] },
    { id: 't12', laneId: 'l5', phaseId: 'ph2', content: 'Engage customer', tags: [] },
    { id: 't13', laneId: 'l5', phaseId: 'ph3', content: 'Provide sample', tags: ['moment-that-matters'] },
    { id: 't14', laneId: 'l5', phaseId: 'ph3', content: 'Get signature', tags: ['moment-that-matters'] },
    { id: 't15', laneId: 'l5', phaseId: 'ph4', content: 'Log transaction', tags: ['moment-that-matters'] },
    { id: 't16', laneId: 'l7', phaseId: 'ph2', content: 'Review compliance', tags: [] },
    { id: 't17', laneId: 'l8', phaseId: 'ph1', content: 'Prepare samples', tags: [] },
    { id: 't18', laneId: 'l8', phaseId: 'ph3', content: 'Ship samples', tags: [] },
    { id: 't19', laneId: 'l9', phaseId: 'ph3', content: 'Deliver package', tags: ['delight'] },
    { id: 't20', laneId: 'l6', phaseId: 'ph3', content: 'ABL process A', tags: [] },
    { id: 't21', laneId: 'l6', phaseId: 'ph3', content: 'ABL process B', tags: [] },
    { id: 't22', laneId: 'l6', phaseId: 'ph3', content: 'ABL process C', tags: [] },
    { id: 't23', laneId: 'l6', phaseId: 'ph4', content: 'ABL complete', tags: [] },
    { id: 't24', laneId: 'l10', phaseId: 'ph2', content: 'CRM entry', tags: [] },
    { id: 't25', laneId: 'l11', phaseId: 'ph3', content: 'Training module', tags: [] },
    { id: 't26', laneId: 'l11', phaseId: 'ph4', content: 'Training complete', tags: [] },
  ],
  connections: [
    { id: 'c1', fromTaskId: 't7', toTaskId: 't8', handoffType: 'human' },
    { id: 'c2', fromTaskId: 't8', toTaskId: 't9', handoffType: 'human' },
    { id: 'c3', fromTaskId: 't9', toTaskId: 't10', handoffType: 'human' },
    { id: 'c4', fromTaskId: 't11', toTaskId: 't12', handoffType: 'human' },
    { id: 'c5', fromTaskId: 't12', toTaskId: 't13', handoffType: 'crm' },
    { id: 'c6', fromTaskId: 't13', toTaskId: 't14', handoffType: 'physical' },
    { id: 'c7', fromTaskId: 't14', toTaskId: 't15', handoffType: 'system' },
    { id: 'c8', fromTaskId: 't9', toTaskId: 't13', handoffType: 'human' },
    { id: 'c9', fromTaskId: 't17', toTaskId: 't18', handoffType: 'physical' },
    { id: 'c10', fromTaskId: 't18', toTaskId: 't19', handoffType: 'physical' },
  ],
};
